[tool.ruff]
line-length = 120

[tool.ruff.lint]
# Additionally enable the following rules
# - pyflakes (`F`)
# - pycodestyle errors (`E`)
# - pycodestyle warnings (`W`)
# - flake8-bugbear warnings (`B`)
# - isort import sorting (`I`)
# - pep8-naming convenrtions (`N`)
# - pyupgrade prefer newer language constructs (`UP`)
select = ["F", "E", "B", "W", "I", "N", "UP"]
