hidden_dim: 256
action_context_length: 100
trajectory_prediction_length: 10
epochs: 500
batch_size: 16
lr: 1.e-4
train_denoising_timesteps: 1000
image_context_length: 10
imu_context_length: 100
num_imu_encoder_layers: 2
joint_state_context_length: 100
num_normalization_samples: 1000
num_joints: 20
use_action_history: True
num_action_history_encoder_layers: 2
use_imu: True
imu_orientation_embedding_method: "quaternion"
num_imu_encoder_layers: 2
use_joint_states: True
joint_state_encoder_layers: 2
use_images: True
image_sequence_encoder_type: "transformer"
image_encoder_type: "resnet18"
num_image_sequence_encoder_layers: 1
num_decoder_layers: 4
distill_teacher_inference_steps: 30