hidden_dim: 512
action_context_length: 100
trajectory_prediction_length: 10
epochs: 15
batch_size: 32
lr: 1.e-4
train_denoising_timesteps: 1000
image_context_length: 10
imu_context_length: 100
joint_state_context_length: 100
num_normalization_samples: 1000
num_joints: 20
use_action_history: True
num_action_history_encoder_layers: 4
use_imu: True
imu_orientation_embedding_method: "quaternion"
num_imu_encoder_layers: 4
use_joint_states: True
joint_state_encoder_layers: 4
use_images: True
image_sequence_encoder_type: "transformer"
image_encoder_type: "resnet18"
num_image_sequence_encoder_layers: 1
num_decoder_layers: 8
distill_teacher_inference_steps: 30
use_gamestate: True
encoder_patch_size: 1
use_robot_type: False