name: Create DB with dummy data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install

    - name: Create DB schema
      run: poetry run cli db create-schema

    - name: Populate DB with dummy data
      run: poetry run cli db dummy-data -n 2
