name: Create DB with example data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_dataset:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: 3.10.x
          - os: ubuntu-24.04
            python-version: 3.12.x
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Create DB schema
        run: poetry run cli db create-schema

      - name: Populate DB with dummy data
        run: |
          poetry run cli db create-schema
          poetry run cli db dummy-data -n 2 -s 100 -i 10

      - name: Test rosbag import with invalid training data fails
        run: |
          curl -fsSLO https://data.bit-bots.de/ROSbags/robocup_2024/ID_donna_2024-07-18T15%3A20%3A44/ID_donna_2024-07-18T15%3A20%3A44_0.mcap
          poetry run cli db create-schema

          set +e
          poetry run cli import rosbag ID_donna_2024-07-18T15%3A20%3A44_0.mcap

          if [ $? -eq 1 ]; then
            echo "Import failed as expected"
          else
            echo "Import should have failed!"
            exit 1
          fi


      - name: Test rosbag import with valid training data
        run: |
          curl -fsSLO https://data.bit-bots.de/ROSbags/robocup_2024/ID_donna_2024-07-20T15%3A49%3A20/ID_donna_2024-07-20T15%3A49%3A20_0.mcap
          poetry run cli db create-schema
          poetry run cli import rosbag ID_donna_2024-07-20T15%3A49%3A20_0.mcap
